class Seeder
  COUNTRIES = [
    [1,   'AD', 'Andorra', 'EUR', 0],
    [2,   'AE', 'United Arab Emirates', 'AED', 0],
    [3,   'AF', 'Afghanistan', 'AFA', 0],
    [4,   'AG', 'Antigua and Barbuda', 'XCD', 0],
    [5,   'AI', 'Anguilla', 'XCD', 0],
    [6,   'AL', 'Albania', 'ALL', 0],
    [7,   'AM', 'Armenia', 'AMD', 0],
    [8,   'AN', 'Netherlands Antilles', 'ANG', 0],
    [9,   'AO', 'Angola', 'AON', 0],
    [10,  'AQ', 'Antarctica', 'NOK', 1],
    [11,  'AR', 'Argentina', 'ARA', 1],
    [12,  'AS', 'American Samoa', 'USD', 0],
    [13,  'AT', 'Austria', 'EUR', 0],
    [14,  'AU', 'Australia', 'AUD', 1],
    [15,  'AW', 'Aruba', 'AWG', 0],
    [16,  'AZ', 'Azerbaijan', 'AZM', 0],
    [17,  'BA', 'Bosnia and Herzegovina', 'BAM', 0],
    [18,  'BB', 'Barbados', 'BBD', 0],
    [19,  'BD', 'Bangladesh', 'BDT', 0],
    [20,  'BE', 'Belgium', 'EUR', 0],
    [21,  'BF', 'Burkina Faso', 'XAF', 0],
    [22,  'BG', 'Bulgaria', 'BGL', 0],
    [23,  'BH', 'Bahrain', 'BHD', 0],
    [24,  'BI', 'Burundi', 'BIF', 0],
    [25,  'BJ', 'Benin', 'XAF', 0],
    [26,  'BM', 'Bermuda', 'BMD', 0],
    [27,  'BN', 'Brunei Darussalam', 'BND', 0],
    [28,  'BO', 'Bolivia', 'BOB', 1],
    [29,  'BR', 'Brazil', 'BRR', 1],
    [30,  'BS', 'Bahamas', 'BSD', 0],
    [31,  'BT', 'Bhutan', 'BTN', 0],
    [32,  'BV', 'Bouvet Island', 'NOK', 0],
    [33,  'BW', 'Botswana', 'BWP', 1],
    [34,  'BY', 'Belarus', 'BYR', 0],
    [35,  'BZ', 'Belize', 'BZD', 1],
    [36,  'CA', 'Canada', 'CAD', 1],
    [37,  'CC', 'Cocos  Islands', 'AUD', 0],
    [38,  'CD', 'Congo', 'XAF', 0],
    [39,  'CF', 'Central African Republic', 'XAF', 0],
    [40,  'CG', 'Congo', 'XAF', 1],
    [41,  'CH', 'Switzerland', 'CHF', 0],
    [42,  'CI', 'Cote d’Ivoire', 'XAF', 0],
    [43,  'CK', 'Cook Islands', 'NZD', 0],
    [44,  'CL', 'Chile', 'CLF', 1],
    [45,  'CM', 'Cameroon', 'XAF', 0],
    [46,  'CN', 'China', 'CNY', 0],
    [47,  'CO', 'Colombia', 'COP', 1],
    [48,  'CR', 'Costa Rica', 'CRC', 1],
    [49,  'CS', 'Serbia and Montenegro', 'CSD', 0],
    [50,  'CU', 'Cuba', 'CUP', 1],
    [51,  'CV', 'Cape Verde', 'CVE', 0],
    [52,  'CX', 'Christmas Island', 'AUD', 0],
    [53,  'CY', 'Cyprus', 'CYP', 0],
    [54,  'CZ', 'Czech Republic', 'CZK', 0],
    [55,  'DE', 'Germany', 'EUR', 0],
    [56,  'DJ', 'Djibouti', 'DJF', 0],
    [57,  'DK', 'Denmark', 'DKK', 0],
    [58,  'DM', 'Dominica', 'XCD', 0],
    [59,  'DO', 'Dominican Republic', 'DOP', 0],
    [60,  'DZ', 'Algeria', 'DZD', 0],
    [61,  'EC', 'Ecuador', 'USD', 1],
    [62,  'EE', 'Estonia', 'EEK', 0],
    [63,  'EG', 'Egypt', 'EGP', 1],
    [64,  'EH', 'Western Sahara', 'MAD', 0],
    [65,  'ER', 'Eritrea', 'ERN', 0],
    [66,  'ES', 'Spain', 'EUR', 0],
    [67,  'ET', 'Ethiopia', 'ETB', 0],
    [240, 'FC', 'Corsica', 'EUR', 0],
    [68,  'FI', 'Finland', 'EUR', 0],
    [69,  'FJ', 'Fiji', 'FJD', 0],
    [70,  'FK', 'Falkland Islands', 'FKP', 0],
    [71,  'FM', 'Micronesia', 'USD', 0],
    [72,  'FO', 'Faeroe Islands', 'DKK', 0],
    [73,  'FR', 'France', 'EUR', 0],
    [74,  'GA', 'Gabon', 'XAF', 0],
    [75,  'GB', 'United Kingdom', 'GBP', 0],
    [76,  'GD', 'Grenada', 'XCD', 0],
    [77,  'GE', 'Georgia', 'GEL', 0],
    [78,  'GF', 'French Guiana', 'EUR', 0],
    [79,  'GH', 'Ghana', 'GHC', 0],
    [80,  'GI', 'Gibraltar', 'GIP', 0],
    [81,  'GL', 'Greenland', 'DKK', 0],
    [82,  'GM', 'Gambia', 'GMD', 0],
    [83,  'GN', 'Guinea', 'GNS', 0],
    [84,  'GP', 'Guadaloupe', 'EUR', 0],
    [85,  'GQ', 'Equatorial Guinea', 'XAF', 0],
    [86,  'GR', 'Greece', 'EUR', 0],
    [87,  'GS', 'South Georgia and the South Sandwich Islands', 'GBP', 0],
    [88,  'GT', 'Guatemala', 'GTQ', 1],
    [89,  'GU', 'Guam', 'USD', 0],
    [90,  'GW', 'Guinea-Bissau', 'GWP', 0],
    [91,  'GY', 'Guyana', 'GYD', 0],
    [92,  'HK', 'Hong Kong', 'HKD', 0],
    [93,  'HM', 'Heard and McDonald Islands', 'AUD', 0],
    [94,  'HN', 'Honduras', 'HNL', 1],
    [95,  'HR', 'Hrvatska', 'HRK', 0],
    [96,  'HT', 'Haiti', 'HTG', 0],
    [97,  'HU', 'Hungary', 'HUF', 0],
    [98,  'ID', 'Indonesia', 'IDR', 1],
    [99,  'IE', 'Ireland', 'EUR', 0],
    [100, 'IL', 'Israel', 'ILS', 0],
    [101, 'IN', 'India', 'INR', 1],
    [102, 'IO', 'British Indian Ocean Territory', 'GBP', 0],
    [103, 'IQ', 'Iraq', 'IQD', 0],
    [104, 'IR', 'Iran', 'IRR', 0],
    [105, 'IS', 'Iceland', 'ISK', 0],
    [106, 'IT', 'Italy', 'EUR', 1],
    [107, 'JM', 'Jamaica', 'JMD', 0],
    [108, 'JO', 'Jordan', 'JOD', 0],
    [109, 'JP', 'Japan', 'JPY', 0],
    [110, 'KE', 'Kenya', 'KES', 1],
    [111, 'KG', 'Kyrgyz Republic', 'KGS', 0],
    [112, 'KH', 'Cambodia', 'KHR', 1],
    [113, 'KI', 'Kiribati', 'AUD', 0],
    [114, 'KM', 'Comoros', 'KMF', 0],
    [115, 'KN', 'St. Kitts and Nevis', 'XCD', 0],
    [116, 'KP', 'Korea', 'KPW', 0],
    [117, 'KR', 'Korea', 'KRW', 0],
    [118, 'KW', 'Kuwait', 'KWD', 0],
    [119, 'KY', 'Cayman Islands', 'KYD', 0],
    [120, 'KZ', 'Kazakhstan', 'KZT', 0],
    [121, 'LA', 'Lao People’s Democratic Republic', 'LAK', 1],
    [122, 'LB', 'Lebanon', 'LBP', 0],
    [123, 'LC', 'St. Lucia', 'XCD', 0],
    [124, 'LI', 'Liechtenstein', 'CHF', 0],
    [125, 'LK', 'Sri Lanka', 'LKR', 1],
    [126, 'LR', 'Liberia', 'LRD', 0],
    [127, 'LS', 'Lesotho', 'LSL', 0],
    [128, 'LT', 'Lithuania', 'LTL', 0],
    [129, 'LU', 'Luxembourg', 'EUR', 0],
    [130, 'LV', 'Latvia', 'LVL', 0],
    [131, 'LY', 'Libyan Arab Jamahiriya', 'LYD', 0],
    [132, 'MA', 'Morocco', 'MAD', 0],
    [133, 'MC', 'Monaco', 'EUR', 0],
    [134, 'MD', 'Moldova', 'MDL', 0],
    [135, 'MG', 'Madagascar', 'MGF', 1],
    [136, 'MH', 'Marshall Islands', 'USD', 0],
    [137, 'MK', 'Macedonia', 'MKD', 0],
    [138, 'ML', 'Mali', 'XAF', 0],
    [139, 'MM', 'Myanmar', 'MMK', 1], # Birmanie
    [140, 'MN', 'Mongolia', 'MNT', 0],
    [141, 'MO', 'Macao', 'MOP', 0],
    [142, 'MP', 'Northern Mariana Islands', 'USD', 0],
    [143, 'MQ', 'Martinique', 'EUR', 0],
    [144, 'MR', 'Mauritania', 'MRO', 0],
    [145, 'MS', 'Montserrat', 'XCD', 0],
    [146, 'MT', 'Malta', 'MTL', 0],
    [147, 'MU', 'Mauritius', 'MUR', 1],
    [148, 'MV', 'Maldives', 'MVR', 1],
    [149, 'MW', 'Malawi', 'MWK', 1],
    [150, 'MX', 'Mexico', 'MXN', 1],
    [151, 'MY', 'Malaysia', 'MYR', 0],
    [152, 'MZ', 'Mozambique', 'MZM', 1],
    [153, 'NA', 'Namibia', 'NAD', 1],
    [154, 'NC', 'New Caledonia', 'XPF', 0],
    [155, 'NE', 'Niger', 'XOF', 0],
    [156, 'NF', 'Norfolk Island', 'AUD', 0],
    [157, 'NG', 'Nigeria', 'NGN', 0],
    [158, 'NI', 'Nicaragua', 'NIC', 1],
    [159, 'NL', 'Netherlands', 'EUR', 0],
    [160, 'NO', 'Norway', 'NOK', 0],
    [161, 'NP', 'Nepal', 'NPR', 1],
    [162, 'NR', 'Nauru', 'AUD', 0],
    [163, 'NU', 'Niue', 'NZD', 0],
    [164, 'NZ', 'New Zealand', 'NZD', 0],
    [165, 'OM', 'Oman', 'OMR', 1],
    [166, 'PA', 'Panama', 'PAB', 1],
    [167, 'PE', 'Peru', 'PEI', 1],
    [168, 'PF', 'French Polynesia', 'XPF', 0],
    [169, 'PG', 'Papua New Guinea', 'PGK', 0],
    [170, 'PH', 'Philippines', 'PHP', 0],
    [171, 'PK', 'Pakistan', 'PKR', 0],
    [172, 'PL', 'Poland', 'PLN', 0],
    [173, 'PM', 'St. Pierre and Miquelon', 'EUR', 0],
    [174, 'PN', 'Pitcairn Island', 'NZD', 0],
    [175, 'PR', 'Puerto Rico', 'USD', 0],
    [176, 'PS', 'Palestinian Territory', 'ILS', 0],
    [177, 'PT', 'Portugal', 'EUR', 0],
    [178, 'PW', 'Palau', 'USD', 0],
    [179, 'PY', 'Paraguay', 'PYG', 0],
    [180, 'QA', 'Qatar', 'QAR', 0],
    [181, 'RE', 'Reunion', 'EUR', 0],
    [182, 'RO', 'Romania', 'ROL', 0],
    [183, 'RU', 'Russian Federation', 'RUB', 0],
    [184, 'RW', 'Rwanda', 'RWF', 0],
    [185, 'SA', 'Saudi Arabia', 'SAR', 0],
    [186, 'SB', 'Solomon Islands', 'SBD', 0],
    [187, 'SC', 'Seychelles', 'SCR', 1],
    [188, 'SD', 'Sudan', 'SDP', 0],
    [189, 'SE', 'Sweden', 'SEK', 0],
    [190, 'SG', 'Singapore', 'SGD', 0],
    [191, 'SH', 'St. Helena', 'SHP', 0],
    [192, 'SI', 'Slovenia', 'SIT', 0],
    [193, 'SJ', 'Svalbard & Jan Mayen Islands', 'NOK', 0],
    [194, 'SK', 'Slovakia', 'SKK', 0],
    [195, 'SL', 'Sierra Leone', 'SLL', 0],
    [196, 'SM', 'San Marino', 'EUR', 0],
    [197, 'SN', 'Senegal', 'XOF', 0],
    [198, 'SO', 'Somalia', 'SOS', 0],
    [199, 'SR', 'Suriname', 'SRG', 0],
    [200, 'ST', 'Sao Tome and Principe', 'STD', 0],
    [201, 'SV', 'El Salvador', 'SVC', 0],
    [202, 'SY', 'Syrian Arab Republic', 'SYP', 0],
    [203, 'SZ', 'Swaziland', 'SZL', 0],
    [204, 'TC', 'Turks and Caicos Islands', 'USD', 0],
    [205, 'TD', 'Chad', 'XAF', 0],
    [206, 'TF', 'French Southern Territories', 'EUR', 0],
    [207, 'TG', 'Togo', 'XAF', 0],
    [208, 'TH', 'Thailand', 'THB', 1],
    [209, 'TJ', 'Tajikistan', 'TJR', 0],
    [210, 'TK', 'Tokelau', 'NZD', 0],
    [211, 'TL', 'Timor-Leste', 'USD', 0],
    [212, 'TM', 'Turkmenistan', 'TMM', 0],
    [213, 'TN', 'Tunisia', 'TND', 1],
    [214, 'TO', 'Tonga', 'TOP', 0],
    [215, 'TR', 'Turkey', 'TRL', 0],
    [216, 'TT', 'Trinidad and Tobago', 'TTD', 0],
    [217, 'TV', 'Tuvalu', 'AUD', 0],
    [218, 'TW', 'Taiwan', 'TWD', 0],
    [219, 'TZ', 'Tanzania', 'TZS', 1],
    [220, 'UA', 'Ukraine', 'UAH', 0],
    [221, 'UG', 'Uganda', 'UGS', 1],
    [222, 'UM', 'United States Minor Outlying Islands', 'USD', 0],
    [223, 'US', 'United States of America', 'USD', 1],
    [224, 'UY', 'Uruguay', 'UYU', 0],
    [225, 'UZ', 'Uzbekistan', 'UZS', 0],
    [226, 'VA', 'Holy See', 'EUR', 0],
    [227, 'VC', 'St. Vincent and the Grenadines', 'XCD', 0],
    [228, 'VE', 'Venezuela', 'VEB', 1],
    [229, 'VG', 'British Virgin Islands', 'USD', 0],
    [230, 'VI', 'US Virgin Islands', 'USD', 0],
    [231, 'VN', 'Viet Nam', 'VND', 1],
    [232, 'VU', 'Vanuatu', 'VUV', 0],
    [233, 'WF', 'Wallis and Futuna Islands', 'XPF', 0],
    [234, 'WS', 'Samoa', 'WST', 0],
    [235, 'YE', 'Yemen', 'YER', 0],
    [236, 'YT', 'Mayotte', 'EUR', 0],
    [237, 'ZA', 'South Africa', 'ZAR', 1],
    [238, 'ZM', 'Zambia', 'ZMK', 1],
    [239, 'ZW', 'Zimbabwe', 'ZWD', 1],
    [241, '',   'Amazonie', '', 1],
    [242, '',   'Galapagos', '', 1],
    [243, '',   'Ile de Paques', '', 1],
    [244, '',   'Yunan', '', 1],
    [245, '',   'Zanzibar', '', 1],
  ].freeze

  VAT_COUNTRIES = %w(AT BE BG CY CZ DE DK EE ES FI FR GB GR HU IE IT LT LU LV MT NL PL PT RO SE SI SK FC MC).freeze
  
  def seed_countries
    seeding 'countries'
    clear_table 'countries'
    progress do
      COUNTRIES.each do |country|
        active = country[4].present?
        name = I18n.t("c_#{country[1].to_s.upcase}", :scope => :countries, :default => country[2])
        values_clause = (country + [name]).map { |v| cnx.quote(v) }.join(', ')
        sql = "INSERT INTO countries (id, code, english_name, currency_code, active, name) VALUES (#{values_clause})"
        cnx.insert(sql)
        ahead!
      end
    end
    Country.where(['code not in (?)', VAT_COUNTRIES]).update_all(uses_vat: false)
    Country.where(code: VAT_COUNTRIES).update_all(uses_vat: true)
  end
end

